# Generated by Django 4.2.4 on 2023-09-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tva_customuser_role_manager_item_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/item_images'),
        ),
    ]
