# Generated by Django 4.2.4 on 2023-09-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_accounting_company_customuser_role_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='compnay',
            new_name='company',
        ),
    ]
