# Generated by Django 4.2.4 on 2023-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_company_subunit_customuser_role_unit_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
