# Generated by Django 4.2.4 on 2023-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_unite_remove_item_tva_alter_item_change_inv_acc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_good',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('mid', 'Mid'), ('finish', 'Finished')], default='finished', max_length=10, null=True),
        ),
    ]
