# Generated by Django 4.2.4 on 2023-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_item_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
