# Generated by Django 4.2.4 on 2023-08-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_accountant_dob_accountant_gender_auditor_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Accountant',
        ),
        migrations.DeleteModel(
            name='Auditor',
        ),
    ]
