# Generated by Django 4.2.4 on 2023-09-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_item_tva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='TTC',
            new_name='ttc',
        ),
    ]
