# Generated by Django 4.2.4 on 2023-09-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supcode', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('TVA', models.BooleanField(default=False)),
                ('TVA_value', models.FloatField(blank=True, null=True)),
                ('TTC', models.FloatField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('addValueCost', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('purchase', models.FloatField(blank=True, null=True)),
                ('expense', models.FloatField(blank=True, null=True)),
                ('final_good', models.BooleanField(default=True)),
                ('change_inv_acc', models.BooleanField(default=False)),
                ('inventory_acc', models.CharField(choices=[('A', 'Inventory Account A'), ('B', 'Inventory Account B')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/item_images')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app1.manager')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
