# Generated by Django 4.2.4 on 2023-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_ttc_item_ttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tva',
            field=models.FloatField(blank=True, choices=[(0.05, '5%'), (0.1, '10%'), (0.2, '20%')], null=True),
        ),
    ]
