# Generated by Django 4.2.4 on 2023-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_item_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tva',
            field=models.FloatField(blank=True, choices=[(0.05, '5%'), (0.1, '10%'), (0.0, '0%')], null=True),
        ),
    ]
