# Generated by Django 4.2.4 on 2023-09-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_item_code_alter_item_name_alter_item_supcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
