# Generated by Django 4.2.4 on 2023-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inventory_acc',
            field=models.CharField(blank=True, choices=[('A', 'Inventory Account A'), ('B', 'Inventory Account B')], default='A', max_length=20, null=True),
        ),
    ]
