# Generated by Django 4.2.4 on 2023-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_item_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tva',
            field=models.FloatField(blank=True, choices=[('null', '0%'), (0.05, '5%'), (0.1, '10%')], null=True),
        ),
    ]
